# https://zohaib.me/managing-secrets-in-nixos-home-manager-with-sops/
keys:
  - &host_hostname age1sqehjv4qjw23kdkp6m7vdqql30ssuasq2hekz0az4ruluvvzg9sqner0k6
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *host_hostname
