{
  config,
  pkgs,
  ...
}:
let
  run-github-mcp-server = pkgs.writeShellApplication {
    name = "run-github-mcp-server";
    text = ''
      # This script is generated by home.nix.
      # It sets the token by reading the file that sops-nix creates at runtime.
      GITHUB_PERSONAL_ACCESS_TOKEN=$(cat ${config.sops.secrets.github_personal_access_token.path})
      export GITHUB_PERSONAL_ACCESS_TOKEN
      # Now, execute the real server binary, which is also in the PATH.
      exec github-mcp-server "$@"
    '';
  };
in
{
  # ixpkgs.config.allowUnfreePredicate = (pkg: true);

  # This value determines the Home Manager release that your
  # configuration is compatible with. This helps avoid breakage
  # when a new Home Manager release introduces backwards
  # incompatible changes.
  #
  # You can update Home Manager without changing this value. See
  # the Home Manager release notes for a list of state version
  # changes in each release.
  home.stateVersion = "24.11";

  # Let Home Manager install and manage itself.
  # programs.home-manager.enable = true;

  home.keyboard = {
    layout = "us";
    variant = "qwerty";
    options = ["ctrl:nocaps"];
  };
  programs.git = {
    enable = true;
    settings.user = {
      name = "jevin";
      email = "jevin@quickjack.ca";
    };
  };
  programs.difftastic = {
    enable = true;
    git.enable = true;
  };

  sops = {
    age.keyFile = "/home/jevin/.config/sops/age/keys.txt"; # must have no password!
    defaultSopsFile = ./secrets.yaml;
    secrets = {
      openrouter_api_key = {};
      openai_api_key = {};
      anthropic_api_key = {};
      gemini_api_key = {};
      github_personal_access_token = {};
      restic_password = {};
      grafana_homelab_secret = {};
      n8n_api_key = {};
      obsidian_api_key = {};
    };
  };

  services.restic = {
    enable = true;
    backups = {
      "synology" = {
        repository = "rest:http://restic-server.apps:8000/postgresql";
        passwordFile = config.sops.secrets.restic_password.path;
        initialize = false;
      };
    };
  };

  home.packages = [ run-github-mcp-server ];
}
